kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leaf-hub-status-sync
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies
  - policies/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - hub-of-hubs.open-cluster-management.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - placementrules
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - delete
