kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leaf-hub-status-sync
subjects:
- kind: ServiceAccount
  name: leaf-hub-status-sync
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: leaf-hub-status-sync
  apiGroup: rbac.authorization.k8s.io
