kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leaf-hub-spec-sync
subjects:
- kind: ServiceAccount
  name: leaf-hub-spec-sync
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: leaf-hub-spec-sync
  apiGroup: rbac.authorization.k8s.io
