kind: Deployment
apiVersion: apps/v1
metadata:
  name: hub-of-hubs-addon-controller
  labels:
    app: hub-of-hubs-addon-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-of-hubs-addon-controller
  template:
    metadata:
      labels:
        app: hub-of-hubs-addon-controller
    spec:
      serviceAccountName: hub-of-hubs-addon-controller-sa
      containers:
      - name: hub-of-hubs-addon-controller
        image: quay.io/clyang82/hub-of-hubs-addon-controller:v0.1.0
        imagePullPolicy: Always
        args:
          - "/hub-of-hubs-addon-controller"
          - "controller"
          - "--v=2"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
